# Generated by Django 4.2.3 on 2023-07-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('founding_date', models.DateField(verbose_name='Дата основания')),
                ('demonym', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название жителей')),
                ('ruler', models.CharField(max_length=255, verbose_name='Под управлением')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('population', models.IntegerField(verbose_name='Количество жителей')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'default_related_name': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('founding_date', models.DateField(verbose_name='Дата основания')),
                ('demonym', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название жителей')),
                ('ruler', models.CharField(max_length=255, verbose_name='Под управлением')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('population', models.IntegerField(verbose_name='Количество жителей')),
                ('official_language', models.CharField(max_length=255, verbose_name='Официальный язык')),
                ('government_type', models.CharField(max_length=255, verbose_name='Тип правления')),
                ('currency', models.CharField(max_length=255, verbose_name='Валюта')),
                ('capital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photos.city', verbose_name='Столица')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'default_related_name': 'capital',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
                'default_related_name': 'items',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Картинка')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрено администратором')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.country', verbose_name='Страна')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.item', verbose_name='Вещь')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'default_related_name': 'photos',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='city',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.item', verbose_name='Вещь'),
        ),
    ]
