# Generated by Django 4.2.3 on 2023-07-23 10:53

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('photos_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
