# Generated by Django 4.2.3 on 2023-07-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_managers_city_slug_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.city', verbose_name='Город'),
        ),
    ]
